teamterning/Terning-Server

src/main/java/org/terning/terningserver/exception/CustomException.java, src/main/java/org/terning/terningserver/exception/GlobalExceptionHandler.java, src/main/java/org/terning/terningserver/exception/dto/ErrorResponse.java, src/main/java/org/terning/terningserver/exception/dto/SuccessResponse.java, src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java, src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java
- 공통 에러처리 및 응답 설정의 초기 세팅을 작업합니다!
- ErrorResponse의 경우 status, message, List<ValidationError> errors 를 함께 반환합니다. 
- 한 번에 반환하는 경우 복잡도가 올라갈 수 있으나 기존 요구사항 구현에 집중하기 위해서 볼륨을 줄이는 방향으로 코드 방향을 잡는 것이 현재 상황에 적합하다고 판단됩니다.
- closed #3 
- 프로젝트 구조
```java
public record SuccessStatusResponse(
int status,
String message
) {
public static SuccessStatusResponse of(SuccessMessage successMessage) {
return new SuccessStatusResponse(successMessage.getStatus(), successMessage.getMessage());
}
}
```
- 위 코드는 status와 message를 분리해서 관리하는 response의 return 값인데요! 이런 방식은 추후에 변동이 생기면 대처하기 용이할 것 같다는 생각이 듭니다. 
- 이러한 방법에 대한 장단점을 인식한 뒤 개발을 진행하다 복잡도가 높아지는 순간이 온다면 이러한 방법들도 고려해 보는 것도 좋을 것 같습니다.
=> [✅ chore/#3]: 공통 에러 처리 및 응답 초기 설정 

src/main/java/org/terning/terningserver/TerningserverApplication.java, src/main/java/org/terning/terningserver/domain/Advertisement.java, src/main/java/org/terning/terningserver/domain/Company.java, src/main/java/org/terning/terningserver/domain/Filter.java, src/main/java/org/terning/terningserver/domain/InternshipAnnouncement.java, src/main/java/org/terning/terningserver/domain/Scrap.java, src/main/java/org/terning/terningserver/domain/User.java, src/main/java/org/terning/terningserver/domain/common/BaseTimeEntity.java, src/main/java/org/terning/terningserver/domain/enums/AuthType.java, src/main/java/org/terning/terningserver/domain/enums/Color.java, src/main/java/org/terning/terningserver/domain/enums/CompanyCategory.java, src/main/java/org/terning/terningserver/domain/enums/Grade.java, src/main/java/org/terning/terningserver/domain/enums/State.java, src/main/java/org/terning/terningserver/domain/enums/WorkingPeriod.java
- 도메인 설정 및 연관관계 매핑
- closed #14 
- Datagrip 로컬 연동 테스트 완료
- 테이블의 속성들이 nullable인지 아닌지 논의가 필요합니다.
- Advertisement 테이블의 속성에 무엇이 들어가야하는지 논의가 필요합니다.
- User 테이블에서 email(이메일)과 userImage(유저프로필아이콘)을 어떻게 저장할지에 대해 논의가 필요합니다.
- 한 엔티티에서 많은 속성들을 가지고 있어 데이터 응집력이 떨어진다고 판단했고, 재사용성을 고려해 InternshipAnnouncement 테이블의 기업 관련 속성들은 company 임베디드 속성으로 그룹화 시켰습니다.
- Date 타입 관련 블로그 링크
https://gngsn.tistory.com/169
- Embedded 타입 관련 블로그 링크
https://velog.io/@conatuseus/JPA-%EC%9E%84%EB%B2%A0%EB%94%94%EB%93%9C-%ED%83%80%EC%9E%85embedded-type-8ak3ygq8wo
=> [✨feat/#14] 도메인 설정 및 연관관계 매핑

src/main/java/org/terning/terningserver/domain/enums/Grade.java, src/main/java/org/terning/terningserver/domain/enums/WorkingPeriod.java, src/main/java/org/terning/terningserver/exception/dto/ErrorResponse.java, src/main/java/org/terning/terningserver/exception/dto/SuccessResponse.java, src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java
- 성공/에러 메시지 필드 및 enum 수정
- closed #20 
- 따로 없음
>  7/9일 서버-클라이언트 로그인 회의 후 나온 수정사항들을 반영했습니다!
1. 성공 및 에러 메시지 필드 수정
- 성공시 : status, message, result
- 실패시: status, result
- 수정 사항) 
1. 필드명 code > status로 수정 / 이유: 조금 더 직관적이고 이해가 잘되는 필드명 사용을 위해
2. validation 예외 발생시 사용되던 errors 필드 삭제 (ErrorResponse 클래스) / 이유: 2차 스프린트로 미루기로 
https://github.com/teamterning/Terning-Server/blob/705591457ddef35b87c7075340daad91e4681b4e/src/main/java/org/terning/terningserver/exception/dto/ErrorResponse.java#L11-L15
https://github.com/teamterning/Terning-Server/blob/705591457ddef35b87c7075340daad91e4681b4e/src/main/java/org/terning/terningserver/exception/dto/SuccessResponse.java#L7-L12
2. enum 타입 수정
- 클라 - 서버 통신에 있어서 받고 보내는 인덱스 값은 무조건 0부터 보내기로 수정하였습니다!
-  이유: 클라에서 0부터 설정하는게 조금 더 편하다고 하셔서!
자세한 회의 내용은 …
=> [✅ chore/#20] 성공/에러 메시지 필드 및 enum 수정

src/main/java/org/terning/terningserver/controller/SearchController.java, src/main/java/org/terning/terningserver/controller/swagger/SearchSwagger.java, src/main/java/org/terning/terningserver/domain/Filter.java, src/main/java/org/terning/terningserver/domain/InternshipAnnouncement.java, src/main/java/org/terning/terningserver/domain/User.java, src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java, src/main/java/org/terning/terningserver/repository/InternshipAnnouncement/InternshipRepositoryCustom.java, src/main/java/org/terning/terningserver/repository/InternshipAnnouncement/InternshipRepositoryImpl.java, src/main/java/org/terning/terningserver/service/SearchService.java, src/main/java/org/terning/terningserver/util/DateUtil.java
- 탐색 > 스크랩 수 많은 공고 API입니다.
- closed #27 
- swagger 문서
<br/>
<br/>
- postman 실행 화면
1. D-Day 계산을 위한 DateUtil 클래스 생성
- 현재 시점이 마감일 보다 이전일 경우 D-Day 계산해서 반환
- 현재 시점이 마감일과 같으면 "D-DAY" 문자열 반환
- 현재 시점이 마감일 이후인 경우 "지원마감" 반환
https://github.com/teamterning/Terning-Server/blob/74af5380daffbd61810e0a35f515afcdc7ef46bb/src/main/java/org/terning/terningserver/util/DateUtil.java#L14-L27
그 외 로직은 👉 closed #26 와 같습니다!
1. User 엔티티 -> 프로필 이미지 캐릭터 필드 추가
https://github.com/teamterning/Terning-Server/blob/1fdee68b7020f67b402bb5580050100dbe1f5e4a/src/main/java/org/terning/terningserver/domain/User.java#L40-L41
2. InternshipAnnouncement, Filter 엔티티 기존의 startDate를 startYear, startMonth로 분리
https://github.com/teamterning/Terning-Server/blob/1fdee68b7020f67b402bb5580050100dbe1f5e4a/src/main/java/org/terning/terningserv …
=> [✨feat/#27] 탐색 > 스크랩 수 많은 공고 API 구현

src/main/java/org/terning/terningserver/controller/HomeController.java, src/main/java/org/terning/terningserver/controller/swagger/HomeSwagger.java, src/main/java/org/terning/terningserver/domain/enums/Color.java, src/main/java/org/terning/terningserver/dto/user/response/TodayScrapResponseDto.java, src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java, src/main/java/org/terning/terningserver/repository/scrap/ScrapRepository.java, src/main/java/org/terning/terningserver/repository/scrap/ScrapRespository.java, src/main/java/org/terning/terningserver/service/HomeServiceImpl.java, src/main/java/org/terning/terningserver/service/ScrapService.java, src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java
- 유저가 스크랩한 공고 중 마감 기한이 오늘(오늘 마감)인 공고데이터의 공고명을 보여준다.
- 보여주는 데이터는 경우의 수가 2가지 있다.
(1) 스크랩된 공고가 없는 경우 & 스크랩된 공고가 있으나, 오늘 마감인 공고가 없는 경우 : 빈 리스트를 반환한다.
(2) 스크랩된 공고가 존재하고, 마감 기한이 오늘인 스크랩 공고도 존재하는 경우 : 유저가 스크랩한 공고 중 서류지원 마감일이 ‘오늘’인 공고 데이터의 스크랩 ID, 인턴쉽 공고ID 와 기업로고 url, title(공고명), dDay, 서류마감, 근무 기간, 근무 시작 년월, 스크랩 색상을 응답으로 준다.
- closed #33 
> Case 1) 스크랩된 공고 가 없는 경우 & 스크랩된 공고가 있으나, 오늘 마감인 공고가 없는 경우 : 빈 리스트 반환
<br/>
> Case 2) 스크랩된 공고가 존재하고, 마감 기한이 오늘인 스크랩 공고도 존재하는 경우 : 유저가 스크랩한 공고 중 서류지원 마감일이 ‘오늘’인 공고 데이터의 스크랩 ID, 인턴쉽 공고ID 와 기업로고 url, title(공고명), dDay, 서류마감, 근무 기간, 근무 시작 년월, 스크랩 색상을 응답으로 준다.
=> [✨feat/#33] 홈화면 > 오늘 마감되는 대학생 인턴 공고 API

src/main/java/org/terning/terningserver/controller/CalendarController.java, src/main/java/org/terning/terningserver/controller/swagger/CalendarSwagger.java, src/main/java/org/terning/terningserver/dto/calendar/response/MonthlyDefaultResponseDto.java, src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java, src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java, src/main/java/org/terning/terningserver/repository/scrap/ScrapRepository.java, src/main/java/org/terning/terningserver/service/ScrapService.java, src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java
- 조회하고자 하는 연도와 월을 입력합니다. 
- 해당하는 년/월의 스크랩한 공고를 deadline별로 그룹화 하여 월간 캘린더(기본 뷰) 정보를 조회합니다. 
- 만약 조회했을 때, 해당하는 스크랩 공고가 없을 경우, 빈 리스트가 조회됩니다.
- closed #36 
- Swagger(200 성공)
- 캘린더 뷰를 담당하는 클라분과 상의 한 결과, 해당 하는 년/월이 서류마감일인 스크랩 공고를 순서대로 띄우는 것과 deadline(서류 마감일) 기준으로 묶어서 정보를 보내주는 과정을 고민했습니다. 
- 리스트로 전달하는 과정에서 stream을 사용하는데, stream 옵션중 최종 단계에서 사용되는 Java Collector인 Stream.collect() stream 요소들을 공부하던 중, 'Collectors.groupingBy()' 를 알게 되었습니다. Collectors.groupingBy() 옵션은 요소를 그룹핑해서 수집하는 역할을 합니다.
- groupingBy collector는 일부 속성 별로 객체를 grouping하고 결과를 Map 인스턴스에 저장하는 데 사용한다고 하여 Map 인스턴스를 활용해 구현했습니다.
https://github.com/teamterning/Terning-Server/blob/890fffed615aa3fd18be60b8d84ae8185f99f747/src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java#L38-L54
- 학습을 하면서 참고했던 블로그 링크를 첨부하겠습니다:)
- [stream 마지막 …
=> [✨feat/#36] 캘린더 > 월간 캘린더(기본 뷰) 정보 조회 API

src/main/java/org/terning/terningserver/controller/CalendarController.java, src/main/java/org/terning/terningserver/controller/swagger/CalendarSwagger.java, src/main/java/org/terning/terningserver/dto/calendar/response/MonthlyListResponseDto.java, src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java, src/main/java/org/terning/terningserver/service/ScrapService.java, src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java
- 조회하고자 하는 연도와 월을 입력하면 해당하는 년/월의 스크랩한 공고를 일별로 보여주는 월간 캘린더(리스트 뷰) 정보 조회 API
- closed #40 
- Swagger(200 성공)
feat/#36 캘린더 > 월간 캘린더(기본 뷰) 정보 조회 API와 동일한 로직에 응답값만 달라져서 크게 변동사항은 없습니다..!
=> [✨feat/#40] 캘린더 > 월간 캘린더(리스트 뷰) 정보 조회 API

src/main/java/org/terning/terningserver/controller/SearchController.java, src/main/java/org/terning/terningserver/controller/swagger/SearchSwagger.java, src/main/java/org/terning/terningserver/domain/InternshipAnnouncement.java, src/main/java/org/terning/terningserver/domain/Scrap.java, src/main/java/org/terning/terningserver/domain/User.java, src/main/java/org/terning/terningserver/domain/enums/Grade.java, src/main/java/org/terning/terningserver/dto/search/response/SearchResultResponse.java, src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java, src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepository.java, src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryCustom.java, src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java, src/main/java/org/terning/terningserver/repository/scarp/ScrapRepository.java, src/main/java/org/terning/terningserver/repository/scarp/ScrapRepositoryCustom.java, src/main/java/org/terning/terningserver/repository/scarp/ScrapRepositoryImpl.java, src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java, src/main/java/org/terning/terningserver/service/SearchService.java, src/main/java/org/terning/terningserver/service/SearchServiceImpl.java
- 검색 결과 화면 API
- closed #31 
- Swagger 문서(API 테스트)
1..collect(Collectors.toList()) > .toList()로 변경
- 저의 로직에서는 리스트가 수정될 필요가 없고, 반환되는 리스트의 수정이 불가능하므로 데이터의 안정성을 높이고자 다음과 같이 변경했습니다!
자세한 사항은 👉[블로그](https://velog.io/@cieroyou/Stream%EC%9D%84-List%EB%A1%9C-%EB%B3%80%ED%99%98%ED%95%98%EB%8A%94-%EB%8B%A4%EC%96%91%ED%95%9C-%EB%B0%A9%EB%B2%95%EA%B3%BC-%EC%B0%A8%EC%9D%B4Collectors.toList-vs-Stream.toList) 첨부해놓겠습니다.
2. 스크랩 여부를 알려주기 위한 쿼리
- 검색 화면의 경우, 인턴공고 리스트와 함께 각각의 인턴 공고를 사용자가 스크랩했다면 scrapId를 함께 Response Body에 넘겨줘야 하는데요!
인턴공고 하나하나마다 해당 인턴공고가 스크랩되었는지를 scrapRepository에서 조회하기에는 조회 쿼리가 너무 많이 나갈 것 같아서 최대한 쿼리를 줄여보고자 했습니다.
따라서 한 번에 인턴 공고에 대한 스크랩 정보를 가져오고, 해당 인턴공고 id와 스크랩 id를 매핑하는 코드를 통해서, 여러번의 검색쿼리를 한 쿼리로 줄일 수 있었습니다! (피드백 대환영🙇‍♀️)
https://github.com/teamterning/Terning-Server/blob/970aa43a5a92bb1e2a5281171b …
=> [✨feat/#31] 검색 결과 화면 API

src/main/java/org/terning/terningserver/controller/CalendarController.java, src/main/java/org/terning/terningserver/controller/swagger/CalendarSwagger.java, src/main/java/org/terning/terningserver/dto/calendar/response/DailyScrapResponseDto.java, src/main/java/org/terning/terningserver/dto/calendar/response/MonthlyDefaultResponseDto.java, src/main/java/org/terning/terningserver/dto/calendar/response/MonthlyListResponseDto.java, src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java, src/main/java/org/terning/terningserver/service/ScrapService.java, src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java
- 조회하고자 하는 연도와 월을 일이 저장된 date를 입력하면 해당하는 날짜의 스크랩한 공고를 보여주는 일간 캘린더 정보 조회 API
- closed #42 
- Swagger(성공 200)
- 해당하는 날짜를 String 타입인 date로 받아왔습니다.
- String(문자열)로 받아오기 때문에 LocalDate.parse("yyyy-mm-dd") 내장 메서드를 이용해서 LocalDate 타입으로 변환해주는 작업을 추가했습니다..!
- 학습 때 참고한 문서를 따로 첨부하겠습니다:)
[Java - String을 파싱하여 LocalDate로 변환하는 방법](https://codechacha.com/ko/java-examples-how-to-convert-string-to-localdate/)
=> [✨feat/#42] 캘린더 > 일간 캘린더(리스트 뷰) 정보 조회 API

src/main/java/org/terning/terningserver/controller/UserProfileController.java, src/main/java/org/terning/terningserver/controller/swagger/CalendarSwagger.java, src/main/java/org/terning/terningserver/controller/swagger/UserSwagger.java, src/main/java/org/terning/terningserver/dto/user/response/ProfileResponseDto.java, src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java, src/main/java/org/terning/terningserver/service/UserService.java, src/main/java/org/terning/terningserver/service/UserServiceImpl.java, src/main/resources/application-dev.yml
- 마이페이지에서 특정 유저의 프로필 정보를 조회하는 API입니다.
- closed #44 
- Swagger(200 성공)
- 우선, 소셜로그인 구현이 완료되지 않았기 때문에  userId == 1로 두고 테스트를 진행 한 후 정상적으로 조회되는 것을 확인하였습니다.
- 토큰을 통해 해당 유저를 특정한 후, 유저의 이름과 인증타입(카카오, 애플 중 하나)을 응답으로 주는 API입니다.
=> [✨feat/#44] 마이페이지 > 프로필 정보 조회 API

src/main/java/org/terning/terningserver/domain/enums/Color.java, src/main/java/org/terning/terningserver/dto/filter/request/UserFilterRequestDto.java
- UserFilterRequestDto에서 userId 필드 삭제
- closed #82 
- 필터링 재설정 API에서 request header로 ATK를 받고 있기 때문에, UserFilterRequestDto에서 userId 필드를 삭제했습니다.
```java
public record UserFilterRequestDto(
int grade,
int workingPeriod,
int startYear,
int startMonth
) {
}
```
=> [🔨fix/#82]: 필터링 재설정 dto 수정

src/main/java/org/terning/terningserver/dto/user/response/HomeResponseDto.java
- 홈 > 나에게 딱맞는 인턴 공고 조회 응답 데이터 변경
- deadline(yyyy년 mm월 dd일), startYearMonth(yyyy년 mm월)을 추가로 dto로 반환할 수 있도록 적용
- closed #84 
- Swagger(성공 200)
=> [🔥!hotfix/#84] 홈 > 나에게 딱맞는 인턴 공고 조회 응답 데이터 변경

src/main/java/org/terning/terningserver/domain/Filter.java, src/main/java/org/terning/terningserver/domain/User.java, src/main/java/org/terning/terningserver/service/FilterServiceImpl.java
- 필터링 설정 안 한 유저가 재설정시 오류나는  문제 해결
- closed #82 
- 회원가입시 필터링 단계를 안 거친 유저, 즉 filter가 null인 유저가 필터링 재설정을 요청할 시 오류가 나는 문제를 해결했습니다.
```
public void updateUserFilter(UserFilterRequestDto responseDto, Long userId) {
User user = findUser(userId);
Filter filter = user.getFilter();
if(filter != null){
filter.updateFilter(
Grade.fromKey(responseDto.grade()),
WorkingPeriod.fromKey(responseDto.workingPeriod()),
responseDto.startYear(),
responseDto.startMonth()
);
} else {
Filter savedFilter = filterRepository.save(
Filter.builder()
.grade(Grade.fromKey(responseDto.grade()))
.workingPeriod(WorkingPeriod.fromKey(responseDto.workingPeriod()))
.startYear(responseDto.startYear())
.startMonth(responseDto.startMonth())
.build()
);
user.assignFilter(savedFilter); …
```
=> [🔨fix/#82]: 필터릴 재설정 로직 수정

src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java, src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java
- 사용자가 해당 공고를 이미 스크랩했을 경우 예외처리 로직 추가
- closed #91 
- postman 화면
- 스크랩 추가 API에서, 사용자가 이미 해당 공고를 스크랩을 경우, 스크랩 성공처리가 되지 않도록 예외처리 로직을 추가했습니다.
```java
@Override
@Transactional
public void createScrap(Long internshipAnnouncementId, CreateScrapRequestDto request, Long userId) {
//이미 스크랩 했을 경우 예외처리
if(scrapRepository.existsByInternshipAnnouncementIdAndUserId(internshipAnnouncementId, userId)) {
throw new CustomException(EXISTS_SCRAP_ALREADY);
}
InternshipAnnouncement announcement = getInternshipAnnouncement(internshipAnnouncementId);
announcement.updateScrapCount(1);
scrapRepository.save(Scrap.create(
findUser(userId),
getInternshipAnnouncement(internshipAnnouncementId),
findColor(request.color())
));
}
```
=> [🔥 !hotfix/#91]: 사용자가 해당 공고를 이미 스크랩했을 경우 예외처리 로직 추가

src/main/java/org/terning/terningserver/TerningserverApplication.java, src/main/java/org/terning/terningserver/controller/HomeController.java, src/main/java/org/terning/terningserver/controller/swagger/HomeSwagger.java, src/main/java/org/terning/terningserver/domain/Scrap.java, src/main/java/org/terning/terningserver/dto/user/response/HomeAnnouncementsResponseDto.java, src/main/java/org/terning/terningserver/dto/user/response/HomeResponseDto.java, src/main/java/org/terning/terningserver/repository/scrap/ScrapRepositoryCustom.java, src/main/java/org/terning/terningserver/repository/scrap/ScrapRepositoryImpl.java, src/main/java/org/terning/terningserver/service/HomeService.java, src/main/java/org/terning/terningserver/service/HomeServiceImpl.java, src/main/java/org/terning/terningserver/service/KakaoServiceImpl.java
- 기존에는 뷰가 유사하지만 데이터 형식을 다르게 전달된 부분들이 있어, 코드의 통일성과 유지보수성을 높이기 위해 전달되는 데이터의 형식을 최대한 통일하는 작업을 진행했습니다.
- 필터링 된 공고의 총 개수(`totalCount`)를 추가로 보내주도록 수정했습니다. (`HomeAnnouncementsResponseDto`)
- `startYear`, `startMonth` → `startYearMonth`로 변수 통합했습니다.
- 스크랩 추가 & 취소 & 색상 수정시 모두 기존 scrapId에서 `internshipAnnouncementId`로 통신하는 것으로 변경되었으므로 해당 API에서는 더 이상 scrapId가 아닌 `isScrapped`라는 필드로 스크랩 여부를 전달하도록 수정했습니다.
- `isScrapped`가 false(스크랩한 공고가 아닌 경우)인 경우, `color`도 null값을 출력하도록 구현하였습니다.
- Scrap의 Enum에 `getColorToHexValue()` 메서드를 추가하여 헥사값의 컬러를 직접 참조하여 가져올 수 있도록 추가하였습니다.
- closed #97 
- totalCount 출력 + scrapId 삭제 + isScrapped 추가 + color 추가(isScrapped가 false이면 null값 전달)
</br>
- 전달되는 공고가 없을 경우 빈리스트와 totalCount = 0 반환
리뷰어들에게 하고 싶은 말
=> [♻️refactor/#97] [2차] 홈화면 > 딱 맞는 대학생 인턴 공고 : 데이터 형식 및 추가 변동사항 적용

src/main/java/org/terning/terningserver/TerningserverApplication.java, src/main/java/org/terning/terningserver/controller/HomeController.java, src/main/java/org/terning/terningserver/controller/swagger/HomeSwagger.java, src/main/java/org/terning/terningserver/domain/Scrap.java, src/main/java/org/terning/terningserver/dto/calendar/response/DailyScrapResponseDto.java, src/main/java/org/terning/terningserver/dto/calendar/response/MonthlyListResponseDto.java, src/main/java/org/terning/terningserver/dto/user/response/HomeAnnouncementsResponseDto.java, src/main/java/org/terning/terningserver/dto/user/response/HomeResponseDto.java, src/main/java/org/terning/terningserver/dto/user/response/TodayScrapResponseDto.java, src/main/java/org/terning/terningserver/repository/scrap/ScrapRepositoryCustom.java, src/main/java/org/terning/terningserver/repository/scrap/ScrapRepositoryImpl.java, src/main/java/org/terning/terningserver/service/HomeService.java, src/main/java/org/terning/terningserver/service/HomeServiceImpl.java, src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java
- 기존에는 뷰가 유사하지만 데이터 형식을 다르게 전달된 부분들이 있어, 코드의 통일성과 유지보수성을 높이기 위해 전달되는 `데이터의 형식을 통일`하는 작업을 진행했습니다.
- `startYear`, `startMonth` → `startYearMonth`로 변수 통합했습니다.
- 스크랩 추가 & 취소 & 색상 수정시 모두 기존 scrapId에서 `internshipAnnouncementId`로 통신하는 것으로 변경되었으므로 해당 API에서는 더 이상 scrapId가 아닌 `isScrapped`라는 필드로 스크랩 여부를 전달하도록 수정했습니다.
- `isScrapped`는 무조건 true를 전달합니다. (캘린더에는 스크랩한 공고만 보여주므로)
- Scrap의 Enum에 `getColorToHexValue()` 메서드를 이용해 헥사값의 컬러를 직접 참조하여 가져올 수 있도록 변경하였습니다.
- closed #99 
- 홈화면 > 오늘 마감되는 관심공고
- 캘린더 > 일간 캘린더
- 캘린더 > 월간 캘린더 (리스트 뷰)
리뷰어들에게 하고 싶은 말
=> [♻️ refactor] [2차] 홈화면 > 오늘 마감되는 관심 공고 & 캘린더(일간,월간) : 데이터 형식 및 추가 변동사항 적용

src/main/java/org/terning/terningserver/controller/AuthController.java, src/main/java/org/terning/terningserver/domain/User.java, src/main/java/org/terning/terningserver/dto/auth/request/SignUpWithAuthIdRequestDto.java, src/main/java/org/terning/terningserver/service/AuthService.java, src/main/java/org/terning/terningserver/service/AuthServiceImpl.java
- **`SignUpWithAuthIdRequestDto` 생성**: 회원가입 시 필요한 데이터를 담는 DTO(Data Transfer Object)를 새롭게 정의하였습니다.
- **기존 로직 리팩토링**: `AuthController`, `User`, `AuthServiceImpl` 클래스에서 기존에 사용하던 회원가입 로직을 `SignUpWithAuthIdRequestDto`를 활용하도록 변경하였습니다.
- `AuthController`: `signUp` 메서드의 파라미터를 단순화하고, `authService.signUp` 호출 시 새로운 DTO를 사용하도록 수정하였습니다.
- `User` 클래스: 사용하지 않는 메서드를 삭제하고, `updateUser` 메서드를 리팩토링하였습니다.
- `AuthServiceImpl`: 회원가입 로직을 세부 메서드로 분리하여 코드 가독성을 높였습니다.
- `Token` 생성 로직을 분리하여 재사용성을 향상시켰습니다.
- closed #106 
- 이번 리팩토링 작업으로 회원가입 로직이 보다 명확하고 유지보수하기 쉽게 변경되었습니다. 코드 리뷰 시, 새로 추가된 DTO와 메서드 분리에 대해 중점적으로 확인해 주시면 감사하겠습니다.
=> [♻️ refactor/#106] 소셜 로그인 > 토큰 생성 메서드 리팩토링 및 파라미터 간소화 작업

src/main/java/org/terning/terningserver/service/AuthServiceImpl.java
- signIn 메서드 내 여러 책임을 분리하여 가독성과 재사용성을 향상시켰습니다.
- 기존의 조건문을 Optional과 람다 표현식을 활용하여 간결하게 개선했습니다.
- closed #114 
이전 PR에서 의견이 나왔었는데요. private 메서드에 update 로직이 담겨 있으니 transcation을 붙여주는 게 낫다는 의견이 있었거든요, 제 생각에는 private 메서드를 사용하는 메서드에서 transaction을 사용하니, 중복을 제거하고자 붙이지 않아도 문제 없다는 생각이었습니다. 그 메서드를 다르 곳에서 사용하는 것이 아니기 때문에요. 그러나 메서드를 불러서 사용할 수 있다는 문제도 존재합니다. 어떻게 생각하시나요!?
=> [♻️ refactor/#114]: signIn 메서드 리팩토링 및 코드 개선

src/main/java/org/terning/terningserver/controller/UserProfileController.java, src/main/java/org/terning/terningserver/controller/swagger/UserSwagger.java, src/main/java/org/terning/terningserver/domain/User.java, src/main/java/org/terning/terningserver/domain/enums/ProfileImage.java, src/main/java/org/terning/terningserver/dto/auth/request/SignUpRequestDto.java, src/main/java/org/terning/terningserver/dto/auth/request/SignUpWithAuthIdRequestDto.java, src/main/java/org/terning/terningserver/dto/user/request/ProfileUpdateRequestDto.java, src/main/java/org/terning/terningserver/dto/user/response/ProfileResponseDto.java, src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java, src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java, src/main/java/org/terning/terningserver/service/AuthServiceImpl.java, src/main/java/org/terning/terningserver/service/UserService.java, src/main/java/org/terning/terningserver/service/UserServiceImpl.java
- profileImage를 기존에 int 형 인덱스 값에서 ENUM 타입(String) 값으로 변경함에 따라 ENUM 파일을 새로 작성해 주었습니다.
- 온보딩 > 회원가입 API에서 profileImage를 `int` 타입에서 `String` 타입으로 전달 받도록 변경했습니다.
(6개의 String Enum 타입 중 하나: `basic`, `lucky`, `smart`, `glass`, `calendar`, `passion`)
- 프로필 이미지가 null인 경우 기본값인 `basic` 으로 설정되도록 구현하였습니다.
- 마이페이지 > 프로필 정보 불러오기 API에서 profileImage를 함께 보내주도록 response를 수정하였습니다.
(6개의 String Enum 타입 중 하나: `basic`, `lucky`, `smart`, `glass`, `calendar`, `passion`)
- 마이페이지 > 프로필 수정 기능을 추가했습니다.
- 유효하지 않은 프로필 이미지로 수정을 시도할 경우, 예외처리 하여 CustomException을 발생시키도록 구현하였습니다.
- closed #123 
- case 1) Swagger 200
- case 2) Swagger 404 : 유효하지 않은 프로필 이미지로 수정을 시도할 경우
기존의 코드와 변경된 부분이 많고, 회원가입 로직에 코드를 추가했기 때문에 꼼꼼하게 확인해주시면 감사하겠습니다:)
잘못된 부분이 있거나 개선할 부분이 있다면 편하게 말씀해주세요!
=> [✨ feat/#123] 마이페이지 > 프로필 정보 이미지 전달방식 변경 & 마이페이지 > 프로필 수정 기능 추가

src/main/java/org/terning/terningserver/controller/ScrapController.java, src/main/java/org/terning/terningserver/domain/enums/Color.java, src/main/java/org/terning/terningserver/dto/scrap/request/CreateScrapRequestDto.java, src/main/java/org/terning/terningserver/dto/scrap/request/UpdateScrapRequestDto.java, src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java, src/main/java/org/terning/terningserver/repository/scrap/ScrapRepository.java, src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java
> 스크랩(취소, 색상 수정) API
- 기존 scrapId로 소통하던 것에서 통일성을 위해 internshipAnnouncmentId로 소통하도록 수정
> 스크랩 color enum 필드 수정
- 기존 int -> string으로 관리
- closed #96 
- 스크랩 취소
</br>
- 스크랩 추가
리팩할 부분이나 보완할 부분은 편하게 코리 달아주세요~!
=> [♻️ refactor/#96]: 스크랩 관련 API -> path variable 수정 및 color enum 필드 수정

build.gradle, src/main/java/org/terning/terningserver/controller/FilterController.java, src/main/java/org/terning/terningserver/controller/ScrapController.java, src/main/java/org/terning/terningserver/controller/swagger/FilterSwagger.java, src/main/java/org/terning/terningserver/controller/swagger/ScrapSwagger.java, src/main/java/org/terning/terningserver/domain/enums/Color.java, src/main/java/org/terning/terningserver/domain/enums/Grade.java, src/main/java/org/terning/terningserver/domain/enums/WorkingPeriod.java, src/main/java/org/terning/terningserver/dto/auth/request/SignUpFilterRequestDto.java, src/main/java/org/terning/terningserver/dto/filter/request/UpdateUserFilterRequestDto.java, src/main/java/org/terning/terningserver/dto/filter/response/UserFilterDetailResponseDto.java, src/main/java/org/terning/terningserver/service/FilterService.java, src/main/java/org/terning/terningserver/service/FilterServiceImpl.java, src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java, src/main/java/org/terning/terningserver/util/LogAspect.java, src/main/java/org/terning/terningserver/util/LogExecutionTime.java
- 필터링 관련 API 수정 및 Spring AOP를 사용한 성능테스트 환경 구축
- closed #127 
- 필터링 재설정
- 사용자 필터링 정보 조회
> 필터링 관련 API 2개 데이터 형식 변경
- 지난 클-서 회의때 인덱스 값을 `int`에서 `String`으로 보내기로 데이터형식을 맞추었기에 해당 2개의 API에서 `workingPeriod`와 `grade` 필드의 타입이 기존 `int`에서 `String`으로 변경되었습니다.
✚ 추가) 사용자 필터링 생성 API도 `WorkingPeriod`와 `Grade` enum의 `key` 타입이 변경됨에 따라 약간의 수정이 있었습니다! 해당사항 수정 후 API 테스트까지 잘 되는 것 확인했습니다.
<br/>
> Spring AOP를 사용한 성능테스트 환경 구축
- 이전 PR에서 정교님께서 findColor()시에 색상수정은 번번하게 일어날 것 같아서 순회탐색보다는 map을 통한 캐싱을 추천해주셨는데요!
해당 사항을 참고하여 두 방안에 대한 성능테스트를 진행해보았습니다.
1. 기존 순회 탐색의 경우
- 시간 복잡도: O(n) / 데이터 개수 n개일 경우
```java
private Color findColor(String color) {
return Arrays.stream(Color.values())
.filter(c-> c.getName().equals(color))
.findAny().get();
}
```
<br/>
2. map을 사용한 캐싱
- 시간 복잡도: O(1)
```java
private static final Map<String, …
```
=> [♻️ refactor/#127]: 필터링 관련 API 수정 및 Spring AOP를 사용한 성능테스트 환경 구축

src/main/java/org/terning/terningserver/service/AuthServiceImpl.java
- 토큰 생성 메서드명을 `getToken()`에서 `getFullToken()`으로 변경하여 명확성을 높였습니다.
- `findUser()` 메서드를 `findUserById()` 및 `findUserByRefreshToken()`으로 각각 변경하여 메서드 명명 규칙을 일관되게 유지했습니다.
- 메서드의 접근 제어자를 수정하여 필요한 경우 `protected`로 변경해 캡슐화를 개선했습니다.
- 데이터베이스 상태를 변경하는 메서드들에 `@Transactional`을 추가하여 트랜잭션 관리가 제대로 이루어지도록 수정했습니다.
- closed #121 
- 메서드 명명 변경 및 트랜잭션 처리가 코드 흐름에 잘 맞는지 중점적으로 리뷰 부탁드립니다.
- 추가적으로 캡슐화 관련 접근 제어자 변경이 적절한지 확인해 주시면 감사하겠습니다.
- [Spring Transactional Documentation](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/transaction/annotation/Transactional.html)
=> [♻️ refactor/#121]: AuthServiceImpl 리팩토링: 메서드 명명 일관성 및 트랜잭션 관리 개선

build.gradle, src/main/java/org/terning/terningserver/controller/FilterController.java, src/main/java/org/terning/terningserver/controller/ScrapController.java, src/main/java/org/terning/terningserver/controller/swagger/FilterSwagger.java, src/main/java/org/terning/terningserver/controller/swagger/ScrapSwagger.java, src/main/java/org/terning/terningserver/domain/enums/Color.java, src/main/java/org/terning/terningserver/domain/enums/Grade.java, src/main/java/org/terning/terningserver/domain/enums/WorkingPeriod.java, src/main/java/org/terning/terningserver/dto/auth/request/SignUpFilterRequestDto.java, src/main/java/org/terning/terningserver/dto/filter/request/UpdateUserFilterRequestDto.java, src/main/java/org/terning/terningserver/dto/filter/response/UserFilterDetailResponseDto.java, src/main/java/org/terning/terningserver/dto/internship_detail/InternshipDetailResponseDto.java, src/main/java/org/terning/terningserver/dto/search/response/SearchResultResponseDto.java, src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java, src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java, src/main/java/org/terning/terningserver/repository/scrap/ScrapRepository.java, src/main/java/org/terning/terningserver/service/FilterService.java, src/main/java/org/terning/terningserver/service/FilterServiceImpl.java, src/main/java/org/terning/terningserver/service/InternshipDetailService.java, src/main/java/org/terning/terningserver/service/InternshipDetailServiceImpl.java, src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java, src/main/java/org/terning/terningserver/service/SearchServiceImpl.java, src/main/java/org/terning/terningserver/util/LogAspect.java, src/main/java/org/terning/terningserver/util/LogExecutionTime.java
- 공고 상세 정보 및 검색 결과 화면 response body 수정
- closed #129
- 공고 상세 페이지 API
<br/>
- 검색 결과 화면 API
바뀐 수정사항은 아래와 같습니다!!
> 공고 상세 정보 API 수정사항
- startDate(근무시작일) 필드명을 startYearMonth 로 수정(다른 API와의 통일성을 위해)
- color 필드 추가
- 스크랩 여부(기존 scrapId > isScrapped, 스크랩 추가 & 취소 & 색상 수정시 모두 기존 scrapId에서 internshipAnnouncementId로 통신하는 것으로 변경되었으므로)
<br/>
> 검색 결과 화면 API
- totalCount 필드 추가 (전체 데이터 개수)
- 스크랩 여부(기존 scrapId > isScrapped, 스크랩 추가 & 취소 & 색상 수정시 모두 기존 scrapId에서 internshipAnnouncementId로 통신하는 것으로 변경되었으므로)
=> [♻️ refactor/#129]: 공고 상세 정보 및 검색 결과 화면 response body 수정

src/main/java/org/terning/terningserver/dto/user/response/UpcomingScrapResponseDto.java
- 디자인 사항이 변경되었으며, 이에 따라 기존의 응답에서 기업명(companyInfo)만 추가로 반환하도록 수정하였습니다!
- closed #131 
- Swagger 200
- 현재 클라 측에서 해당 사항 반영을 조금 미뤄달라고 말씀주셔서 클라(어요,안드) 모두 가능할 때 해당 사항 반영할 예정입니다!
- 그 전까지 추가적인 변경사항이 생길 경우 해당 브랜치에 변경사항 반영하겠습니다:)
=> [♻️ refactor/#131] 홈화면 > 곧 마감되는 관심 공고 전달 데이터 수정

src/main/java/org/terning/terningserver/controller/AuthController.java, src/main/java/org/terning/terningserver/controller/swagger/AuthSwagger.java
- 소셜 로그인, 토큰 재발급, 필터링 정보 생성, 회원가입 API에 대한 Swagger 주석 추가 및 설명 보완
- API 문서와 Swagger 설명 간의 불일치 문제 해결
- closed #134 
- Swagger 설명과 API 문서 간의 차이를 중점적으로 봐주시면 감사하겠습니다. 추가로 필요한 설명이나 수정 사항이 있다면 코멘트 부탁드립니다.
- 기존 방식에서는 name과 description 박스를 개별적으로 컨트롤할 수 없었습니다. 이러한 상황에서, 클라이언트가 박스 안의 값을 보고 더 쉽게 이해할 수 있도록 개선 방향을 잡았고, 그 결과 description에 'Example:'이 표시되더라도 example 값을 사용하였습니다.
- [Swagger 공식 문서](https://swagger.io/docs/)
- [Springfox Swagger 설정 관련 문서](https://springfox.github.io/springfox/docs/current/)
=> [♻️ refactor] 소셜로그인 > Swagger와 API 문서 간 정보 불일치 수정

src/main/java/org/terning/terningserver/controller/HomeController.java, src/main/java/org/terning/terningserver/dto/user/response/UpcomingScrapResponseDto.java, src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java, src/main/java/org/terning/terningserver/repository/scrap/ScrapRepository.java, src/main/java/org/terning/terningserver/service/ScrapService.java, src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java
- 현재 곧 마감되는 공고 UI의 응답 흐름은 다음과 같습니다.
스크랩된 공고 X, 곧 마감 공고 X -> "아직 스크랩된 인턴 공고가 없어요!"
스크랩된 공고 O, 곧 마감 공고 X -> "공고 마감 일정 확인하기"
스크랩된 공고 O, 곧 마감 공고 O -> 공고 정보 보여주기
현재는 이렇게 구성되어 있으나, 분기처리를 위해 유저가 스크랩한 공고가 있는지를 알아야 하는데 곧 마감 공고 API에서는 알 수가 없는 문제가 있습니다.
곧 마감 공고 API에 유저가 스크랩한 공고가 있는지 여부(hasScrapped)를 response에 추가하여
스크랩을 했으나 곧 마감되는 공고가 없는 것인지와
스크랩한 공고가 아예없는 것인지 각각에 대한 분기처리를 명확히 구분했습니다!
- closed #137
=> [♻️ refactor] 홈 > 곧 마감되는 관심공고 : 분기 처리를 위한 데이터 형식 추가

src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java, src/main/java/org/terning/terningserver/service/AuthServiceImpl.java
- 회원가입 관련 상태 코드를 더 적절하게 수정했습니다.
- 회원가입 실패 시 `401 Unauthorized`에서 `400 Bad Request`로 변경.
- 이미 존재하는 유저일 경우 `401 Unauthorized`에서 `409 Conflict`로 변경.
- `AuthServiceImpl`에서 잘못된 리프레시 토큰 사용 시 예외 처리를 `INVALID_USER`에서 `FAILED_TOKEN_REISSUE`로 수정.
- closed #141
- 클라이언트 사이드에서 회원가입 관련 이슈가 있다고 해서 서버 로직을 확인했지만, 서버 로직에는 문제가 없었습니다. 
- 클라이언트 로직을 함께 살펴보고 문제를 해결하였으며, 그 과정에서 상태 코드 수정 요청이 있었습니다. 
- 회원가입 실패 및 중복 유저 관련 상태 코드를 더 명확하게 하기 위해 수정했으니, 코드 변경 사항을 확인해 주시기 바랍니다.
- 상태 코드 변경이 서버와 클라이언트 간 통신에 문제가 없도록 추가적인 검토를 부탁드립니다.
- [HTTP 상태 코드 관련 문서](https://developer.mozilla.org/ko/docs/Web/HTTP/Status)
=> [🔨fix] 회원가입 관련 상태 코드 수정 및 예외 처리 변경

src/main/java/org/terning/terningserver/service/AuthServiceImpl.java
- 회원가입 시 authId에서 'Bearer ' 문자열을 제거하는 로직을 추가했습니다.
- 로그아웃 후 재로그인 시 토큰이 제대로 반환되지 않는 문제가 있었는데, 이 또한 'Bearer ' 문자열로 인해 발생한 문제임을 확인했습니다.
- authId를 기준으로 사용자를 찾지 못해 신규 회원으로 잘못 인식된 문제도 함께 해결했습니다.
- closed #147 
- authId 사용 시 'Bearer ' 문자열을 제거하도록 변경했습니다. 이로 인해 발생했던 로그인 문제도 해결된 상태입니다. 다른 토큰 처리 로직과 충돌 가능성이 없는지 한 번 더 검토 부탁드립니다.
- JWT 토큰 처리 관련 참고 자료: [[jwt.io](https://jwt.io/introduction)]
=> [🔨 fix/#147] 소셜 로그인 > authId 전처리

src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java
- 불필요한 중복 에러 메시지 제거 및 코드 정리
- 계정 탈퇴 시 잘못된 404 에러 코드를 400 에러 코드로 수정
- closed #143
- 계정 탈퇴 실패 관련 에러 코드 변경 사항을 검토 부탁드립니다.
- 이외 다른 에러 메시지 중에서도 불필요한 중복이 있을 수 있으니 확인 부탁드립니다.
- 현재 회원가입을 할 때 클라이언트 측에서만 검증 로직을 처리하고 서버에서는 따로 검증을 하지 않고 있는데, 이번 기회에 서버에서도 검증 로직을 도입하려고 합니다. 이에 대한 의견을 듣고 싶습니다.
- 또한, 기존의 소셜 로그인 상태 코드들에 대해서도 전반적인 의견을 부탁드립니다.
- [HTTP 응답 상태 코드](https://developer.mozilla.org/ko/docs/Web/HTTP/Status)
=> [♻️ refactor/#143]: 불필요한 중복 에러 메시지 제거 및 코드 정리

src/main/java/org/terning/terningserver/repository/user/UserRepository.java, src/main/java/org/terning/terningserver/service/AuthServiceImpl.java, src/main/java/org/terning/terningserver/service/WebhookService.java
- [✨feat/#144] Discord 회원가입 알림 구현
- `Discord`의 웹 훅 기능을 연동하여 유저가 회원가입 시 디스코드에 알림 메시지가 발송되도록 구현하여, 현재 유저가 얼마나 가입했는지 직관적으로 확인할 수 있는 기능을 구현하였습니다.
- closed #144 
- Discord 알림 예시
[참고링크](https://velog.io/@hanni/Spring-Boot3-%EC%83%88%EB%A1%9C%EC%9A%B4-%EB%A9%A4%EB%B2%84%EA%B0%80-%EA%B0%80%EC%9E%85%ED%96%88%EC%8A%B5%EB%8B%88%EB%8B%A4-%EB%94%94%EC%8A%A4%EC%BD%94%EB%93%9C-%ED%9A%8C%EC%9B%90%EA%B0%80%EC%9E%85-%EC%95%8C%EB%A6%BC-%EC%9B%B9%ED%9B%85-%EB%A7%8C%EB%93%A4%EA%B8%B0)
=> [✨ feat/#144] Discord 회원가입 알림 구현

src/main/java/org/terning/terningserver/domain/InternshipAnnouncement.java, src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java
- 검색화면 totalPages, totalCount 데이터 부정확한 오류 수정 
- closed #140 
- postman
, 스웨거, 포스트맨 등
다시 돌아왔슴다.. 데이터 부정확한 문제가 해결되지 않아서 몇 시간 동안 삽질하였음니다.. 이번에는 원인을 제대로 찾은 것 같아요 ...
문제 원인은 아래와 같습니다.
> left join()으로 인한 데이터 중복
지난 번에 `fetchjoin()`이 내부적으로 `innerjoin()`으로 작동하여 데이터 중복이 있었다고 말씀드렸는데요! 이번에는 `leftjoin()`으로 인한 데이터 중복 문제가 있었습니다... `leftjoin()`은 데이터 중복 문제가 없는 줄 알았습니다..!
- `InternshipAnnouncement`와 `scrap` 테이블을 `internshipAnnounctmentId`를 기준으로 조인할 경우, 하나의 인턴공고는 다중의 사용자로부터 스크랩될 수 있기 때문에 조인했을 경우 아래 사진과 같이 중복 데이터가 생기게 됩니다..!
https://neverfadeaway.tistory.com/20
=> [🔨 fix/#140] 검색화면 totalPages, totalCount 데이터 부정확한 오류 수정 

src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java
- 우선 PR이 늦어진 점 죄송함다..🙇‍♀️ 
- closed #이슈번호
- 영어 대소문자 구분없이 공고 검색 가능
<br/>
- 한글 띄어쓰기 관계없이 공고 검색 가능
> 기존에는 영어 대소문자에 따라 검색이 불가능했었는데, 로직을 수정했습니다! 우선 플로우는 아래와 같습니다.
- 영어 대소문자 구분없이 검색 가능하도록
- ex) "Naver", "NAVER"
- 띄어쓰기 구분
- 검색어가 영어로만 이루어질 경우, 띄어쓰기 지켜야함 ex) Naver != na ver
- 한글을 포함한 경우 띄어쓰기 무시 ex) "딜라이트 지원"과 "딜라이트지원" 모두 가능
<br/>
1. 영어 대소문자 구분없이 검색 가능하도록 -> LOWER() 사용
- 해당 함수는 오직 영문자에 대해서만 유효하게 동작하며, 대소문자 구분이 없는 한글 또는 특수기호 등은 해당 메서드를 적용해도 변화가 없다고 하네요!
https://github.com/teamterning/Terning-Server/blob/b7f20cd352d636932367eb5a830e960b523dc7ef/src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java#L66
<br/>
2. 검색어가 순수 영문명인지, 아닌지(한글, 숫자포함) 판단 -> 정규 표현식 사용
https://github.com/teamterning/Terning-Server/blob/b7f20cd352d636932367eb5a830e960b523dc7ef/src/ma …
=> [🔨fix/#160] 인턴 공고 검색 로직 수정

src/main/java/org/terning/terningserver/util/DateUtil.java
- [♻️refactor] DateUtil에서 디데이를 계산할 때, 전체 일자를 고려해 날짜가 계산되도록 수정했습니다.
- 오늘 날짜가 10월 27일 일 때, 10월 31일 공고는 D-4로 정상적으로 뜬다. 하지만 12월 31일 공고 또한 'D-4'로 동일하게 표기가 되는 현상을 발견했습니다.
- 디데이 계산 로직에 전체적인 deadline이 아닌 날짜만 반영되어 계산되어 생기는 오류로, `ChronoUnit.DAYS` 를 사용하여 deadline과 오늘 날짜 사이의 정확한 일 수를 계산하도록 `DateUtil.java` 로직을 수정했습니다.
- closed #166 
-  오늘 날짜 10/27 <> 마감 날짜 12/31 (D-4가 아닌 D-65로 출력)
=> [♻️refactor] DateUtil에서 디데이를 계산할 때, 전체 일자를 고려해 날짜가 계산되도록 수정

src/main/java/org/terning/terningserver/service/FilterServiceImpl.java
- `updateUserFilter` 메서드를 리팩토링하여 단일 책임 원칙을 적용했습니다.
- **`else` 문 제거**: `if-return` 패턴을 도입해 코드의 흐름을 단순화하고 가독성을 향상했습니다. 
- `else` 문 제거로 중첩된 로직이 사라져, 필터가 존재하지 않는 경우 새로운 필터를 바로 생성하도록 처리했습니다.
- **업데이트와 생성 로직 분리**: 필터 업데이트는 `updateExistingFilter` 메서드로, 필터 생성은 `createNewFilter` 메서드로 분리하여 책임을 명확히 했습니다.
- **중복 제거**: `Grade.fromKey`와 `WorkingPeriod.fromKey` 호출을 한 번만 수행하고, 변환된 값을 매개변수로 전달하도록 변경했습니다.
- `findUser` 메서드를 통해 사용자 조회 시, 미조회 상황에서는 커스텀 예외를 던지도록 처리했습니다.
1. **코드 간결화**: `else` 문 제거와 메서드 분리로 코드가 더욱 직관적이고 깔끔해졌습니다.
2. **유지보수성 향상**: 각 메서드가 하나의 책임만 수행하도록 설계하여 수정 및 확장이 용이해졌습니다.
3. **재사용성 증가**: 중복된 로직 제거로 코드 재사용성이 높아졌습니다.
4. **효율성 개선**: 변환 작업을 단일 호출로 축소하여 성능이 향상되었습니다.
- closed #173 
- 이번 작업에서는 **`else` 문 제거**와 **메서드 분리**를 통해 가독성과 코드 품질을 개선했습니다. 
- `if-return` 패턴을 적용해 코드의 흐름을 명확히 하고 중복 로직을 줄였습니다.
- 필터 …
=> [♻️ refactor/#173]: updateUserFilter 메서드 리팩토링

src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryCustom.java, src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java, src/main/java/org/terning/terningserver/service/HomeServiceImpl.java, src/test/java/org/terning/terningserver/test_plan.jmt
- 현재 코드는 scrapRepository를 각 InternshipAnnouncement마다 호출함으로써 데이터베이스 접근이 비효율적으로 이루어지고 있어 해당 부분을 리펙토링하였습니다. (N+1 문제 발생)
- `QueryDSL Tuple`을 활용해 [**홈 - 나에게 딱 맞는 공고 API**]의 `공고 조회` 로직 성능을 크게 개선했습니다.
- `Scrap` 정보를 한 번에 조회 하도록 변경했습니다.
- `Enum` 타입으로 호출하여 컴파일 시 타입체크가 가능하도록 하였고, `Color` Enum의 내부 메서드를 통해 색상값을 불러오도록 수정했습니다.
- 불필요한 메서드를 제거하고, `isScrapped` 로직을 좀 더 단순하게 수정했습니다.
- 변경 전/후의 query 로직에 대한 비교를 위해 `JMeter` 도구를 활용해 성능 테스트를 진행했습니다.
- 대표적인 도구인 `k6`, `nGrinder`, `JMeter` 중 HTML 형식의 보고서가 잘 정리되어 있고, 레퍼런스의 규모와 사용성 측면에서 상당히 이점이 존재하는 JMeter를 사용하여 성능 테스트를 진행했습니다.
- Number Of Threads (users) : `100` -> `100`명의 사용자가 동시에 요청을 보냄
- Ramp-up period (seconds) : `1` -> 부하테스트를 진행할 것이기 때문에 쓰레드 수들을 나눠서 테스트 하지 않음
- Loop Count : Infinite (단, request가 총 `50000`회 응답할때까지 반복)
- Protocol[http] -> http
- Server Name or IP …
=> [♻️ refactor] N+1 문제 해결 및 HomeServiceImpl 성능 개선

src/main/java/org/terning/terningserver/controller/HomeController.java, src/main/java/org/terning/terningserver/controller/swagger/HomeSwagger.java, src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryCustom.java, src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java, src/main/java/org/terning/terningserver/service/HomeService.java, src/main/java/org/terning/terningserver/service/HomeServiceImpl.java, src/test/java/org/terning/terningserver/service/legacy/HomeServicePerformanceTest.java, test_plan.jmt
- [♻️ refactor] 나에게 딱 맞는 대학생 인턴 공고 API Query Parameter 재조정
- 기존의 Query Parameter로 받아왔던 year과 month를 모두 삭제하고, 사용자의 필터링 정보 기반으로 공고를 필터링하도록 로직을 전면 수정했습니다.
- closed #179
=> [♻️ refactor/#179] 나에게 딱 맞는 대학생 인턴 공고 API Query Parameter 재조정

src/main/java/org/terning/terningserver/domain/Filter.java, src/main/java/org/terning/terningserver/domain/enums/JobType.java, src/main/java/org/terning/terningserver/dto/filter/request/UpdateUserFilterRequestDto.java, src/main/java/org/terning/terningserver/dto/filter/response/UserFilterDetailResponseDto.java, src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java, src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java, src/main/java/org/terning/terningserver/service/AuthServiceImpl.java, src/main/java/org/terning/terningserver/service/FilterServiceImpl.java
- [✨ feat] 직무필터링, 사용자 필터링 정보, 필터링 재설정(직무, 계획) API 구현
- 사용자의 직무 필터링(jobType)과 계획 필터링 사항을 모두 한번에 수정하는 필터링 제설정 API와 필터링 정보를 불러오는 API를 구현합니다.
- closed #181 
- 직무필터링이 추가되면서, 직무필터링을 한번도 설정하지 않았던 유저들은 total로 설정되도록 구현했습니다.
- 직무를 Enum으로 관리하고, 해당 필드를 사용해 기존의 응답에 추가로 직무정보를 응답하도록 구현했습니다.
=> [✨ feat] 직무필터링, 사용자 필터링 정보, 필터링 재설정(직무, 계획) API 구현

src/main/java/org/terning/terningserver/controller/HomeController.java, src/main/java/org/terning/terningserver/controller/swagger/HomeSwagger.java, src/main/java/org/terning/terningserver/dto/user/response/HomeAnnouncementsResponseDto.java, src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryCustom.java, src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java, src/main/java/org/terning/terningserver/service/HomeService.java, src/main/java/org/terning/terningserver/service/HomeServiceImpl.java
1. **공고 조회 API에 페이징 기능 추가**
- `Pageable`을 활용하여 페이징 처리 구현.
- `@PageableDefault` 어노테이션을 사용하여 기본 페이지 크기를 10으로 설정하여 유연한 페이징 요청 가능.
2. **DTO 수정**
- `HomeAnnouncementsResponseDto`에 페이징 관련 필드 추가:
- `totalPages`: 전체 페이지 수.
- `hasNext`: 다음 페이지 존재 여부.
3. **Repository 수정**
- 기존에 리스트로 반환하던 공고 데이터를 페이징 처리된 형태로 반환하도록 쿼리 수정.
- `Page<Tuple>` 타입을 활용하여 페이징 로직을 구현하고, 데이터의 효율적 처리를 보장.
- `JPAQueryFactory`를 사용하여 필터 조건을 기반으로 데이터를 페이징 처리하여 조회.
4. **Service 로직 리팩토링**
- 중복된 로직과 책임을 분리하여 공통 메서드로 분리:
- `getUserById`: 사용자 검증 및 조회 책임 분리.
- `createEmptyResponse`: 데이터가 없을 경우 기본 응답을 생성.
- DTO 매핑 로직 분리:
- `mapToHomeResponseDtos`: 조회된 데이터를 DTO 형태로 변환하는 로직.
- `isScrapped`, `determineColorValue`: 스크랩 여부 및 색상 처리 분리.
- 페이징 결과 및 변환된 데이터를 포함한 최종 응답 생성 메서드 추가: `createResponse`.
5. **Swagger 수정**
- 페이징 관련 파라미터(`page`, `size`)를 …
=> [✨feat/#185]: 공고 조회 페이지네이션 기능 도입 및 서비스 로직 개선

src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryCustom.java, src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java, src/main/java/org/terning/terningserver/service/HomeServiceImpl.java
- [🔥 !hotfix] 필터링 정보가 모두 null이면 전체 공고가 보이도록 수정
- closed #191
=> [🔥 !hotfix] 필터링 정보가 모두 null이면 전체 공고가 보이도록 수정

build.gradle, src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java
- 필터링 건너뛰기 시 직무 필터링만 적용되도록 데이터 반환 로직 수정
- jobType만 설정되어 있는 경우에도 해당 직무 공고가 정상적으로 표시될 수 있도록 필터 로직을 수정
- 핵심은 필드별로 null 혹은 기본값(0 등)일 때는 해당 필터 조건을 건너뛰도록 구현해야한다.
- closed #193
=> [🔀 merge] [3차] 코드 리펙토링 사항 적용

src/main/java/org/terning/terningserver/exception/GlobalExceptionHandler.java, src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java, src/main/java/org/terning/terningserver/logging/CachedHttpServletRequest.java, src/main/java/org/terning/terningserver/logging/LoggingFilter.java, src/main/resources/logback-dev.xml, src/main/resources/logback-local.xml, src/main/resources/logback-prod.xml
- HTTP 요청/응답 로깅을 구현했습니다.
- closed #201 
- local 환경 콘솔 예시)
- request
- response
- staging, prod는 머지하고 나서 ec2 접속해서 파일 잘 생성되는지 확인해봐야할 것 같아여!! 우선 staging 환경부터 머지하고 확인하겠습니다~
- 무조건 콘솔에 로그찍히게
- 이유: 빠르게 문제 파악하고, 디버깅 및 테스트를 하는 게 우선시 되어야 한다고 생각
- 로그 레벨: info
<br/>
- 로그 저장 위치: 파일(RollingFileAppender)에 저장
- 파일 경로: `/home/ubuntu/dev-logs/terning.log`
- 로그 패턴:
- `날짜 시각 [스레드명] 로그레벨 로거명 [traceId] - 메시지`
- ex) `2025-03-30 14:21:03 [main] INFO com.example.SomeClass [NoTraceID] - Hello log`
- 참고로 traceId는 추적에 용이하도록 사용하고자 했으며, 하나의 요청/응답은 고유한 traceId를 가지게 됩니다.
- 로그 레벨: INFO
<br/>
- 로그 저장 위치: 파일(RollingFileAppender)에 저장
- 파일 경로: `/home/ubuntu/prod-logs/terning.log`
- 로그 패턴:
- `날짜 시각 [스레드명] 로그레벨 로거명 [traceId] - 메시지`
- ex) `2025-03-30 14:21:03 [main] INFO com.example.SomeClass [NoTraceID] - Hello log`
- 로그 레벨: …
=> [✨ feat] HTTP 요청/응답 로깅 구현

build.gradle, src/main/java/org/terning/terningserver/auth/application/signin/AuthSignInServiceImpl.java, src/main/java/org/terning/terningserver/auth/dto/response/SignInResponse.java, src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java, src/main/java/org/terning/terningserver/external/config/WebClientConfig.java, src/main/java/org/terning/terningserver/external/dto/FcmTokenReissueRequiredResponse.java, src/main/java/org/terning/terningserver/external/notification/FcmTokenValidationClient.java
- 소셜 로그인 시, 해당 유저의 FCM 토큰 유효성을 확인하는 로직을 추가했습니다.  
- 외부 FCM 서버의 토큰 검증 API와 통신하기 위해 `WebClient` 설정(`WebClientConfig`)을 구성했습니다.  
- `FcmTokenValidationClient`를 통해 API 호출 및 결과를 받아오며, `Resilience4j Circuit Breaker`를 적용해 장애 상황에 대한 대응도 고려했습니다.  
- 로그인 응답인 `SignInResponse`에 `fcmTokenReissueRequired` 필드를 추가해서, 클라이언트가 재발금 필요 여부를 판단할 수 있도록 하였습니다.  
- 이로서 클라이언트는 로그인 응답을 통해 FCM 토큰 재발금이 필요한지 여부를 판단하고 필요한 대응을 합니다.
- 로그인 프로세스에 외부 API 호출이 추가되며 네트웨크 이슈나 장애 상황도 고려하게 되어 `CircuitBreaker`를 적용했습니다.  
- 현재는 fallback 시 단순히 `false`를 반환하고 있는데, 이 처리 방식이 적절한지 함께 고민해보면 좋을 것 같습니다.    
- 필드가 늘어난 만큼, 명확하게 활용되도록 API 문서에 반영하겠습니다!
- closed #210
=> [✨ feat] 소셜 로그인 시 FCM 토큰 검증 및 재발급 여부 응답 처리 로직 구현

src/main/java/org/terning/terningserver/config/SecurityConfig.java, src/main/java/org/terning/terningserver/domain/Scrap.java, src/main/java/org/terning/terningserver/domain/vo/SyncStatus.java, src/main/java/org/terning/terningserver/external/scrap/api/ScrapExternalApiController.java, src/main/java/org/terning/terningserver/external/scrap/application/ScrapExternalService.java, src/main/java/org/terning/terningserver/external/scrap/application/UnsyncedScrapUserReader.java, src/main/java/org/terning/terningserver/external/scrap/application/UnsyncedScrapUserReaderImpl.java, src/main/java/org/terning/terningserver/external/scrap/dto/response/UnsyncedScrapUserResponse.java, src/main/java/org/terning/terningserver/external/scrap/dto/response/UnsyncedScrapUsersResponse.java, src/main/java/org/terning/terningserver/repository/scrap/ScrapRepository.java, src/main/java/org/terning/terningserver/repository/scrap/ScrapRepositoryCustom.java, src/main/java/org/terning/terningserver/repository/scrap/ScrapRepositoryImpl.java
- 알림 서버와의 스크랩 동기화를 위해, 동기화되지 않은 스크랩을 가진 유저 목록을 조회하는 API를 구현하였습니다.
- `Scrap` 도메인에 `syncStatus` 임베디드 VO를 추가하여 동기화 여부를 명확히 표현했습니다.
- `/api/v1/external/scraps/unsynced` 경로로 외부에서 접근 가능한 조회 API를 제공하며, 인증 필터에서 해당 경로를 제외 처리하였습니다.
- `UnsyncedScrapUserReader` 인터페이스와 구현체(`UnsyncedScrapUserReaderImpl`)를 통해 조회 책임을 분리하고, 테스트 용이성과 확장성을 고려했습니다.
- DTO (`UnsyncedScrapUserResponse`, `UnsyncedScrapUsersResponse`)를 통해 API 응답 구조를 명확히 구성했습니다.
- 이번 작업에서 `Scrap`, `SyncStatus`, `UnsyncedScrapUserReader`와 같은 네이밍이 직관적인지 고민이 많았습니다.  
- 특히, `SyncStatus`가 boolean을 감싸고 있어 단순해 보일 수도 있는데, 도메인 표현으로 적절한지 의견을 듣고 싶습니다.  
- 또 `UnsyncedScrapUserReaderImpl`이라는 이름이 너무 길진 않은지도 피드백 부탁드립니다!  
- 네이밍 외에도 개선할 점 있다면 편하게 말씀해 주세요!
- 테스트 코드는 작성하려 했으나, 기존 코드의 의존관계가 복잡해 바로 도입하기 어려운 상황이라  
이번 스프린트 종료 후 구조 개선과 함께 적용해보려고 합니다. 양해 부탁드립니다 🙏
- …
=> [✨ feat] 스크랩한 유저를 조회하는 API 구현 

build.gradle, src/main/java/org/terning/terningserver/auth/application/signup/AuthSignUpServiceImpl.java, src/main/java/org/terning/terningserver/auth/dto/request/SignUpRequestDto.java, src/main/java/org/terning/terningserver/external/config/WebClientConfig.java, src/main/java/org/terning/terningserver/external/dto/request/CreateUserRequest.java, src/main/java/org/terning/terningserver/external/notification/NotificationUserClient.java
- closed #212 
운영서버에서 회원가입 시 회원 정보를 dto에 담아 알림서버의 user에 새롭게 추가하도록 구현했어요!
운영서버에서의 유저 id는 알림서버의 oUserId로써 함께 가지고 있을 수 있도록 구현했어요 :)
그리고 알림서버에서의 특정 컬럼은 회원가입 시 기본값으로 초기화 되도록 했어요.
push_status (푸시알림 설정 여부)  > `ENABLED`
account_status (해당 유저의 로그인 여부) > `ACTIVE`
그리고 해당 방식이 동기적으로 구현이 이루어지다보니 아무래도 트래픽이 많이 몰리는 상황에서는 비효율적이라는 생각이 들었어요.
이후 구현할때 메시지 큐를 이용해 비동기적으로 처리하는 것을 고려해보면 좋을 것 같아요..!
=> [✨ feat] 회원가입 시 FCM 토큰 저장 로직 구현

build.gradle, src/main/java/org/terning/terningserver/TerningserverApplication.java, src/main/java/org/terning/terningserver/config/SecurityConfig.java, src/main/java/org/terning/terningserver/controller/UserProfileController.java, src/main/java/org/terning/terningserver/controller/swagger/UserSwagger.java, src/main/java/org/terning/terningserver/domain/User.java, src/main/java/org/terning/terningserver/domain/enums/PushNotificationStatus.java, src/main/java/org/terning/terningserver/dto/user/request/PushStatusUpdateRequest.java, src/main/java/org/terning/terningserver/dto/user/response/ProfileResponseDto.java, src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java, src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java, src/main/java/org/terning/terningserver/external/notification/NotificationUserClient.java, src/main/java/org/terning/terningserver/external/scrap/ScrapSyncMarkerImpl.java, src/main/java/org/terning/terningserver/external/user/application/UserSyncEventService.java, src/main/java/org/terning/terningserver/external/user/application/UserSyncEvnetServiceImpl.java, src/main/java/org/terning/terningserver/external/user/config/NotificationSyncTasklet.java, src/main/java/org/terning/terningserver/external/user/config/UserSyncJobConfig.java, src/main/java/org/terning/terningserver/external/user/domain/UserSyncEvent.java, src/main/java/org/terning/terningserver/external/user/domain/UserSyncEventType.java, src/main/java/org/terning/terningserver/external/user/respository/UserSyncEventRepository.java, src/main/java/org/terning/terningserver/external/user/scheduler/UserSyncScheduler.java, src/main/java/org/terning/terningserver/service/UserService.java, src/main/java/org/terning/terningserver/service/UserServiceImpl.java
- 유저 상태(푸시알림 허용 여부, 유저 이름 변경, 회원 탈퇴) 시 알림서버 <> 운영서버 동기화를 구현했습니다.
- 사용자의 푸시알림 여부를 받아오기 위해, 운영서버의 user에도 pushStatus를 가지도록 추가했습니다.
- 푸시알림 상태변경은 마이페이지 > 유저 푸시알림 상태 변경 API를 추가해 변경하도록 하였습니다.
- 푸시알림 상태확인은 마이페이지 > 유저 프로필 정보 조회 API를 통해 한번에 조회하도록 하였습니다.
- 스케쥴링은 아래와 같이 설정했습니다.
- 푸시 알림(추천 알림)이 오후 1시에 전송되기 30분 전에 사용자 정보 업데이트를 반영하기 위해서 매주 목요일과 토요일 오후 12시 30분에 동기화가 진행되도록 하였습니다.
- 일요일 오후 9시에 전송되는 트렌딩 알림 전에 업데이트가 반영되도록 하기 위해서 매주 일요일 오후 8시 30분에 동기화가 진행되도록 설정했습니다.
- closed #220
=> [✨ feat] 유저 상태(푸시알림 허용 여부, 유저 이름 변경, 회원 탈퇴) 시 알림서버 <> 운영서버 동기화 작업 및 API 구현

.gitignore, build.gradle, src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepository.java, src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java, src/test/java/org/terning/terningserver/service/ScrapServiceTest.java
- 스크랩 취소시, InternshipAnnouncement 테이블의 scrapCount에 대한 Race Condition(경쟁 상태)가 발생하여 데이터 정합성을 보장하기 위해 비관적 락을 적용했습니다.
- closed #222 
- 우선 스크랩 수에 대한 동시성 문제가 있을 줄 몰랐어요.. 리팩을 위해 코드를 보다가 스크랩 수가 부정확하다는 사실을 발견했습니다..
- 아래 사진을 보시면 현재 스크랩 추가/취소 시에 `InternshipAnnouncement` 테이블에서 가지고 있는 `scrapCount`를 증감해주고 있는데요! 스크랩 취소 및 추가 시에 동시성 문제가 발생하여 스크랩 수를 업데이트하는 과정에서 문제가 발생한 것 같아요. 사진을 보시면 공고에 대한 스크랩 데이터는 실제 3개가 존재하는데 `scrapCount`는 4가 저장되어 있었어요.
<br/>
- 실제 `scrapCount`에 대한 `Race Condition`(경쟁 상태)가 발생했는지 파악하기 위해, 테스트 코드를 작성하여 테스트를 해봤습니다.
- 테스트 환경
- DB: h2 인메모리 모드 -> 빠르게 실행하고자 인메모리 모드로 진행했어요.
- 시나리오: 멀티 스레드 환경, 동시에 100개의 API 요청이 왔다고 가정하고, `scrapCount`를 100개로 세팅을 해두고 모두 요청을 처리한 뒤 scrapCount가 0이 되는지 테스트 해보았습니다!
결과는 아래와 같이,, 테스트에 실패했어요. 0을 기대했지만, 결과는 스크랩 수가 71이었고, 스크랩 수라는 자원에 대한 경쟁 상태가 발생했다는 걸 알 수 있었습니다,,
<br/>
- `DB …
=> [🔨 fix] 스크랩 취소시, 스크랩 수에 대한 동시성 이슈를 해결하기 위해 비관적 락 적용

.github/workflows/DOCKER-CD-STAGING.yml, .github/workflows/DOCKER-CD.yml, README.md, src/main/java/org/terning/terningserver/auth/application/signin/AuthSignInServiceImpl.java, src/main/java/org/terning/terningserver/auth/application/social/apple/AppleAuthTokenValidator.java, src/main/java/org/terning/terningserver/auth/dto/request/SignInRequest.java, src/main/java/org/terning/terningserver/auth/dto/response/SignInResponse.java, src/main/java/org/terning/terningserver/config/SwaggerConfig.java, src/main/java/org/terning/terningserver/config/WebMvcConfig.java, src/main/java/org/terning/terningserver/domain/Scrap.java, src/main/java/org/terning/terningserver/external/config/WebClientConfig.java, src/main/java/org/terning/terningserver/external/notification/NotificationUserClient.java, src/main/java/org/terning/terningserver/jwt/provider/JwtKeyProvider.java, src/main/java/org/terning/terningserver/service/UserServiceImpl.java
- closed #228 
작업한 내용이 알림서버와 동일하여 자세한 내용은 아래 PR 주소에서 확인해주세요!
https://github.com/teamterning/Terning-Server-Notification/pull/69
=> [🔨 fix] 서버 QA를 위한 테스트 및 수정 작업 진행

src/main/resources/logback-dev.xml, src/main/resources/logback-prod.xml
- Docker 컨테이너 로그로도 로그 확인할 수 있도록 logback 설정을 수정했습니다!
- closed #227 
> docker logs -f 했는데 실행 로그가 안 보여요..!
- HTTP 요청/응답 로깅을 스테이징 및 운영환경에서는 파일로 로그가 기록되도록 RollingFileAppender만 사용중인 상황이었습니다.
- 이로 인해 **Docker 환경에서 docker logs로 로그가 보이지 않는 문제 발생가 발생했어요.**
- 최근 Docker 컨테이너가 잠깐 올라갔다가 에러로 인해 바로 내려가는 상황이 발생해서 `docker logs -f <컨테이너 id>`로 로그를 확인하려 했더니, SQL 쿼리만 찍히고 아무것도 찍히지 않아서 문제를 파악하기 어려웠습니다.. 
<br/>
우선 제가 설정한 HTTP 요청/응답 로깅과 컨테이너 실행 로그와 어떤 관련이 있는지부터 알아보았는데요!
Docker는 `stdout/stderr` 스트림을 기반으로 로그를 수집한다고 합니다. 하지만 기존의 logback 설정에서는 `RollingFileAppender`만 사용하고 있어, 로그가 파일로만 저장되고 stdout에는 출력되지 않았습니다.
> ⚠️ 결론: 도커는 `stdout/stderr` 스트림을 기반으로 로그를 수집하는데, `logging driver` 가 로그를 파일, 호스트 또는 DB 등에 저장하게 되면 docker logs 명령어로는 로그를 확인할 수 없게 됨.
- 이에 따라 logback 설정에 ConsoleAppender를 추가하고, HTTP 요청/응답을 포함한 주요 로그가 stdout에도 함께 …
=> [🔨 fix] Docker 컨테이너 로그로도 로그 확인할 수 있도록 HTTP 요청/응답 로깅 설정 수정

src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java, src/test/java/org/terning/terningserver/service/ScrapServiceTest.java
- 스크랩 추가시, 스크랩 추가시, 스크랩 수에 대한 동시성 테스트를 진행했습니다 (테스트 코드 작성)
- 이전 PR과 이어지는 내용이에요! 참고 부탁드려요:)
- https://github.com/teamterning/Terning-Server/pull/225
- closed #234 
- 스크랩 추가시 여러 요청이 올 때 스크랩 수와 실제 스크랩 수 테이블의 데이터 개수가 일치하는 지에 대한 동시성 테스트를 진행했어요:)
- 비관적 락 적용은 이전 PR에서 공고 조회시 걸도록 해놓았기 때문에, 해당 PR에서는 테스트 코드를 작성하여 정상적으로 동작하는지 검증했습니다! 
> Scrap 저장 및 scrapCount 업데이트 기능을 실제 DB 연동 및 트랜잭션 처리까지 검증하기 위해 통합테스트(SpringBootTest)로 작성했습니다.
- 아직도 의문이 드는건,,, 저번 PR에 적긴했지만 스크랩수가 불일치하는 문제가 동시성 문제가 맞는지 확신하지 못하겠는 부분이 조금 걸리는 것 같아요..!  
-  현재 스크랩 수 update 후 스크랩 데이터 저장을 하고 있는데, 한 트랜잭션 안에서 일어나다 보니 스크랩 저장 과정에서 에러가 발생해도 롤백이 되어 스크랩 수가 update되지 않을 것이라서,,
https://persi0815.tistory.com/29
=> [🔨 fix] 스크랩 추가시, 스크랩 수에 대한 동시성 테스트 진행

src/main/java/org/terning/terningserver/auth/application/signin/AuthSignInServiceImpl.java, src/main/java/org/terning/terningserver/external/notification/NotificationUserClient.java
- 기존에는 회원가입 시에만 알림서버 DB에 유저를 새롭게 추가하는 방식으로 구현되어있었습니다.
- 하지만, 운영서버가 메인으로 설정되게 되면, 기존 유저의 경우 fcm토큰을 가지고 있지 않고, 알림서버 연결이 안되어있는 상황이였기 때문에, 알림서버에 유저를 소셜로그인 할때도 동기화를 해주어야 합니다.
- 따라서 소셜로그인 시, 알림서버와 운영서버의 유저를 동기화 하는 로직을 추가했습니다.
- 소셜로그인 시, 기존의 알림서버에 토큰 업데이트 요청을 하고, 만약, 유저정보가 존재하지 않는 경우, 알림서버에 해당 유저의 정보를 추가하도록 로직을 구현했습니다.
- closed #238 
**<운영서버>**
**<알림서버>**
=> [feat] 소셜로그인 시, 알림서버와 운영서버의 유저를 동기화 하는 로직 추가

src/main/java/org/terning/terningserver/auth/api/AuthController.java, src/main/java/org/terning/terningserver/auth/api/AuthSwagger.java, src/main/java/org/terning/terningserver/auth/application/AuthService.java, src/main/java/org/terning/terningserver/auth/application/syncUser/AuthSyncUserService.java, src/main/java/org/terning/terningserver/auth/application/syncUser/AuthSyncUserServiceImpl.java, src/main/java/org/terning/terningserver/auth/dto/request/FcmTokenSyncRequest.java, src/main/java/org/terning/terningserver/common/config/SecurityConfig.java, src/main/java/org/terning/terningserver/common/exception/enums/SuccessMessage.java
- 기존 운영서버 유저가 소셜로그인을 다시 하지 않아도 알림서버에 FCM 토큰을 `동기화`할 수 있도록 하기 위한 API 구현했습니다.
- 로그인된 사용자가 홈 화면 진입 시, 유저 정보가 알림서버에 없으면 `새로 등록`하고, 있다면 FCM 토큰만 `갱신`하도록 했습니다.
- `실제 로그인한 유저`만 해당 API를 적용할 수 있도록 사전에 security에서 인증을 요구하도록 어노테이션을 추가했습니다.
- closed #243
=> [✨ feat] 일회성 유저 동기화 API 구현

.github/workflows/DEV-CI.yml, .github/workflows/DOCKER-CD-PRODUCTION.yml, .gitignore, build.gradle, src/main/java/org/terning/terningserver/user/domain/User.java, src/main/resources/application-dev.yml, src/main/resources/application-prod.yml, src/main/resources/application-test.yml, src/main/resources/application.yml, src/test/java/org/terning/terningserver/TerningserverApplicationTests.java, src/test/java/org/terning/terningserver/service/ScrapServiceTest.java
이번 작업은 반복적으로 발생하던 CI/CD 파이프라인 실패 및 배포 중 서버 다운 현상의 근본 원인을 파악하고 해결하기 위해, 프로젝트 전반의 설정 관리 방식과 배포 파이프라인을 현대적인 방식으로 전면 개선하는 것을 목표로 삼았습니다.
파편화되어 있던 설정 정보와 배포 스크립트를 중앙에서 명확하게 관리할 수 있도록 변경하여, 향후 유지보수성과 안정성을 높이는 데 초점을 맞췄습니다.
- application.yml 템플릿화:
- As-Is: 민감 정보가 포함된 yml 파일을 통째로 GitHub Secret에 저장하고, 빌드 시점에 동적으로 생성했습니다. 이는 Secret 관리의 복잡성을 높이고, 이미지 내에 민감 정보가 포함될 위험이 있었습니다.
- To-Be: application.yml을 ${...} 플레이스홀더를 사용하는 안전한 '템플릿'으로 변경했습니다. 이제 Git에는 설정의 '구조'만 남고, 실제 '값'은 실행 시점에 주입되어 보안과 유연성이 크게 향상될 것으로 기대합니다.
- 프로파일 기반 설정 분리 (application-*.yml):
- As-Is: 하나의 거대한 yml 파일에 모든 환경의 설정이 혼재되어 있었습니다.
- To-Be: dev, prod, test 등 각 환경의 고유한 동작 방식(예: ddl-auto: update vs validate)만 각자의 파일에 정의하도록 분리했습니다. 이를 통해 환경별 설정 차이를 명확하게 관리하고, 실수를 방지할 수 있을 것 같아요.
- 안전한 Secret 주입:
- As-Is: 빌드 시점에 Secret을 파일로 생성했습니다.
- To-Be: …
=> [EPIC] 개발-배포-운영 파이프라인 안정성 강화

build.gradle, src/main/java/org/terning/terningserver/common/config/SecurityConfig.java, src/main/java/org/terning/terningserver/external/pushNotification/user/domain/UserSyncEvent.java, src/main/resources/application-test.yml, src/main/resources/application.yml
- 서버의 상태 지표를 수집하고 시각화하기 위해 프로메테우스 및 그라파나 연동을 위한 기반 설정을 추가합니다. Spring Boot Actuator를 통해 메트릭을 노출하고, 프로메테우스가 이를 수집할 수 있도록 관련 의존성, 설정, 보안 규칙을 변경합니다.
모니터링 설정
- build.gradle: 프로메테우스 포맷으로 메트릭을 노출하는 micrometer-registry-prometheus 의존성을 추가했습니다.
- application.yml: management 설정을 통해 /actuator/prometheus 엔드포인트를 웹에 노출하고 활성화했습니다.
- SecurityConfig.java: 프로메테우스가 인증 없이 메트릭을 수집할 수 있도록 /actuator/** 경로를 시큐리티 화이트리스트에 추가했습니다.
코드 리팩토링 및 정리
- UserSyncEvent.java: Enum 타입의 데이터 저장 방식을 ORDINAL에서 STRING으로 변경하여 데이터 정합성과 가독성을 향상시켰습니다.
- application-test.yml: 불필요하게 주석 처리된 중복 설정을 제거했습니다.
- closed #260
=> [FEAT] 모니터링 환경 구축 및 과부화 테스트

src/main/java/org/terning/terningserver/auth/dto/Token.java, src/main/java/org/terning/terningserver/auth/jwt/JwtProvider.java, src/main/java/org/terning/terningserver/auth/jwt/exception/JwtErrorCode.java, src/main/java/org/terning/terningserver/auth/jwt/exception/JwtException.java, src/main/java/org/terning/terningserver/common/config/ValueConfig.java, src/main/java/org/terning/terningserver/common/exception/GlobalExceptionHandler.java, src/main/java/org/terning/terningserver/common/security/jwt/application/JwtClaimsGenerator.java, src/main/java/org/terning/terningserver/common/security/jwt/application/JwtUserIdExtractor.java, src/main/java/org/terning/terningserver/common/security/jwt/auth/JwtClaimsParser.java, src/main/java/org/terning/terningserver/common/security/jwt/auth/UserIdConverter.java, src/main/java/org/terning/terningserver/common/security/jwt/filter/CustomJwtAuthenticationEntryPoint.java, src/main/java/org/terning/terningserver/external/pushNotification/user/domain/UserSyncEvent.java
이번 PR은 Spring Security 의존성을 점진적으로 제거하기 위한 첫 단계로, 기존에 여러 곳에 분산되어 있던 JWT 관련 로직을 auth 도메인 내의 커스텀 JwtProvider로 통합하고 리팩토링하는 작업을 진행했습니다. 이를 통해 인증/인가 코드의 응집도를 높이고 향후 유지보수성을 개선하고자 합니다.
-   `auth` 도메인에 특화된 커스텀 `JwtProvider`를 구현하여 JWT 생성, 검증 및 사용자 ID 추출 로직을 통합했습니다.
- Access Token과 Refresh Token을 함께 반환하기 위한 `Token` DTO를 `record` 형식으로 추가했습니다.
- JWT 관련 예외 처리 클래스(`JwtException`, `JwtErrorCode`)의 패키지 위치를 `common.security`에서 `auth.jwt`로 이동하여 응집도를 높였습니다.
- `JwtProvider` 변경에 따라, 영향을 받는 다른 클래스들의 의존성 및 import 경로를 수정했습니다.
- closed #278
=> Feat : 커스텀 JWT Provider 구현

src/main/java/org/terning/terningserver/auth/dto/response/SignInResponse.java
- 신규 유저가 소셜 로그인을 시도할 때, 클라이언트 측에서 발생하는 응답 데이터 파싱 오류를 해결했습니다.
- **문제 원인**: `SignInResponse` DTO에 적용된 `@JsonInclude(JsonInclude.Include.NON_NULL)` 어노테이션으로 인해, `null` 값을 가진 필드(`accessToken`, `refreshToken` 등)가 JSON 응답에서 제외되었습니다.
- **해결**: 해당 어노테이션을 제거하여, `null` 값을 가진 필드도 항상 응답에 포함되도록 수정했습니다.
- 신규 유저의 소셜 로그인 케이스를 테스트할 때, 응답 JSON 바디에 `accessToken`, `refreshToken`, `userId` 필드가 `null` 값으로 정상적으로 포함되는지 확인 부탁드립니다.
- 이번 수정은 신규 유저의 응답 구조만 변경하며, 기존 유저의 로그인 응답에는 영향을 주지 않습니다.
- closed #297
=> [♻️ refactor/#297] 신규 유저 로그인 시 응답 데이터 누락 문제 해결

src/main/java/org/terning/terningserver/auth/application/AuthService.java
회원가입(`signUp`) 로직에서, `Authorization` 헤더로 받은 `authId`에 포함될 수 있는 **`Bearer ` 접두사를 제거하는 기능을 추가**했습니다. 이를 통해 데이터베이스에는 항상 순수한 소셜 인증 ID만 저장되도록 보장합니다.
기존 가입 유저가 로그인 시도 시 신규 유저로 잘못 인식되어 로그인이 불가능한 문제가 발생했습니다. 원인은 클라이언트가 전달한 `Bearer {authId}` 값을 서버가 파싱하지 않고 그대로 DB에 저장했기 때문입니다.
`Bearer` 접두사를 처리하는 로직의 위치에 대해 고민했습니다.
1.  **`AuthService` (채택)**: 문제 상황이 `signUp` 로직에 한정되어 있고, 비즈니스 로직과의 응집도가 높아 가장 실용적이라고 판단했습니다.
2.  **별도 `Resolver` 객체**: SRP 원칙을 지킬 수 있어 가장 이상적인 구조지만, 현 상황에서는 과엔지니어링이라고 보았습니다.
3.  **`Controller` 계층**: 계층 분리 원칙은 지킬 수 있으나 코드 중복의 우려가 있었습니다.
따라서 현재 구조에서 가장 효율적인 `AuthService`에 로직을 추가하는 것으로 결정했습니다.
---
- 회원가입 시 `authId`를 처리하는 로직의 위치에 대해 다른 의견이 있으시면 편하게 공유해주세요!
- **중요**: 이 PR이 머지되어도, 스테이징 DB에 이미 `Bearer` 접두사와 함께 잘못 저장된 유저 데이터는 **수동으로 수정**해야 정상 로그인이 가능합니다.
- 제가 이 부분은 개선해 둔 상태입니다!
---
- closed #301
=> fix(auth): 회원가입 시 authId의 Bearer 접두사 처리
