- .github/workflows/DOCKER-CD.yml
- Dockerfile
- Docker CI/CD 진행
- closed #이슈번호
리뷰어들에게 하고 싶은 말
> [☁️deploy] Docker CI/CD 

- build.gradle
> ✅ Health_check 의존성 추가

- src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java
- Discord <> Github 연동 테스트 및 쓸모없는 코드 삭제
- closed #12
> [💡test] Discord <> Github 연동 테스트 및 쓸모없는 코드 삭제

- .gitignore
- build.gradle
- src/main/java/org/terning/terningserver/config/QuerydslConfig.java
- QueryDSL 세팅(build.gradle 파일 세팅, Q-Class 생성, .gitignore 처리)
- closed #18 
- Q-Class 생성 확인
이번 PR에서는 3차 공유스터디에서 학습했던 QueryDSL을 적용하기 위한 프로젝트 세팅을 진행했습니다.
build.gradle에서 설정해야 하는 부분들이 많아 각각의 코드에 주석을 달아놨으니 코드 볼때 참고해서 봐주세요!
Q-Class가 정상적으로 생성된 부분까지 확인했습니다!
추가적으로 개선할 사항이나 모르는 부분, 궁금한 부분이 있다면 언제든지 댓글 달아주세요:)
https://natural-louse-039.notion.site/QueryDsl-3383d2fdca1f4a87bfa8deb13fa08ce1
https://www.notion.so/Querydsl-aa4bf01f23e7435eaa0b2c6b17f53dd2?pvs=4
https://www.notion.so/QueryDSL-JPQL-344ad5617d80486d8d62716ab252911b?pvs=4
> [✨feat/#18] QueryDSL 세팅

- .gitignore
- build.gradle
- src/main/resources/application-dev.yml
- src/main/resources/application.yml
- Connection Pool + Hikari CP 세팅
- closed #23 
- Hikari CP 생성 완료
매번 공유문서에서 application.yml 코드를 복사해서 사용해야 하는 번거로움을 해결하기 위해 application.yml의 보안상 문제가 되는 사용자 이름과 암호는 환경 변수로 설정한 이후 .gitignore에서 제거했습니다!
https://velog.io/@dongvelop/Spring-Boot-Hikari-CP-%EC%BB%A4%EC%8A%A4%ED%85%80%EC%9C%BC%EB%A1%9C-%EC%84%B1%EB%8A%A5-%EC%B5%9C%EC%A0%81%ED%99%94%ED%95%98%EA%B8%B0
> [✅chore/#23] Connection Pool + Hikari CP 세팅

- src/main/java/org/terning/terningserver/controller/InternshipDetailController.java
- src/main/java/org/terning/terningserver/controller/ScrapController.java
- src/main/java/org/terning/terningserver/controller/SearchController.java
- src/main/java/org/terning/terningserver/controller/swagger/InternshipDetailSwagger.java
- src/main/java/org/terning/terningserver/controller/swagger/ScrapSwagger.java
- src/main/java/org/terning/terningserver/controller/swagger/SearchSwagger.java
- src/main/java/org/terning/terningserver/domain/Scrap.java
- src/main/java/org/terning/terningserver/domain/enums/Color.java
- src/main/java/org/terning/terningserver/dto/internship_detail/InternshipDetailResponseDto.java
- src/main/java/org/terning/terningserver/dto/scrap/request/CreateScrapRequestDto.java
- src/main/java/org/terning/terningserver/dto/scrap/request/UpdateScrapRequestDto.java
- src/main/java/org/terning/terningserver/dto/search/response/PopularAnnouncementListResponseDto.java
- src/main/java/org/terning/terningserver/dto/search/response/SearchResultResponseDto.java
- src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java
- src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java
- src/main/java/org/terning/terningserver/repository/scrap/ScrapRepository.java
- src/main/java/org/terning/terningserver/service/InternshipDetailService.java
- src/main/java/org/terning/terningserver/service/ScrapService.java
- src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java
- src/main/java/org/terning/terningserver/service/SearchService.java
- src/main/java/org/terning/terningserver/service/SearchServiceImpl.java
- 스크랩(추가/취소/색상 수정) API
- closed #39 
- 스크랩 추가 API
<br/>
<br/>
- 스크랩 취소 API
<br/>
<br/>
- 스크랩 색상 수정 API
매우 간단한 로직이여서 따로 특별히 남길 부분이 없지만...
한가지는, 클라에서 받은 토큰으로 부터 파싱한 user와 실제로 스크랩한 유저가 일치하는지 여부를 검증하는 메서드를 구현했습니다! (일치하지 않는다면, 스크랩 취소 및 수정할 권한이 없으므로..!!)
```
//토큰으로 찾은(요청한) User와 스크랩한 User가 일치한지 여부 검증하는 메서드
private void verifyScrapOwner(Scrap scrap) {
if(!scrap.getUser().equals(findUser(1L))) {
throw new CustomException(FORBIDDEN_DELETE_SCRAP);
}
}
```
> [✨feat/#39] 스크랩(추가/취소/색상 수정) API

- build.gradle
- src/main/java/org/terning/terningserver/controller/AuthController.java
- src/main/java/org/terning/terningserver/domain/Filter.java
- src/main/java/org/terning/terningserver/domain/User.java
- src/main/java/org/terning/terningserver/service/AuthServiceImpl.java
- src/main/java/org/terning/terningserver/service/SignUpFilterService.java
- 설명
- closed #이슈번호
리뷰어들에게 하고 싶은 말
> [🔀 merge] Sign-In 메서드 변경사항 반영

- src/main/java/org/terning/terningserver/controller/FilterController.java
- src/main/java/org/terning/terningserver/controller/swagger/FilterSwagger.java
- src/main/java/org/terning/terningserver/domain/Filter.java
- src/main/java/org/terning/terningserver/dto/filter/request/UserFilterRequestDto.java
- src/main/java/org/terning/terningserver/dto/filter/response/UserFilterResponseDto.java
- src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java
- src/main/java/org/terning/terningserver/service/FilterService.java
- src/main/java/org/terning/terningserver/service/FilterServiceImpl.java
- src/main/java/org/terning/terningserver/service/InternshipDetailService.java
- src/main/java/org/terning/terningserver/service/InternshipDetailServiceImpl.java
- 사용자 필터링 조회 및 재설정 API
- closed #47 
- 사용자 필터링 정보 조회
<br/><br/>
- 사용자 필터링 수정 
우선 수정API의 경우 동적 쿼리를 사용하지 않고 더티체킹(변경감지)를 통해서 수정되게 하였습니다!
```
public void updateFilter(Grade grade, WorkingPeriod workingPeriod, int startYear, int startMonth) {
this.grade = grade;
this.workingPeriod = workingPeriod;
this.startYear = startYear;
this.startMonth = startMonth;
}
```
> [✨ feat/#47] 사용자 필터링 조회 및 재설정 API

- src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java
- src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java
> [🔨 fix/#51] 타입 수정

- src/main/java/org/terning/terningserver/config/WebConfig.java
> [🔥!hotfix/#63] CORS 에러 해결

- src/main/java/org/terning/terningserver/repository/scrap/ScrapRepository.java
- 설명
- closed #이슈번호
리뷰어들에게 하고 싶은 말
> [🔨fix]: 로직수정

- src/main/java/org/terning/terningserver/dto/auth/response/TokenGetResponseDto.java
- 설명
- closed #이슈번호
리뷰어들에게 하고 싶은 말
> [🔨fix#70]: 이슈 재발급 dto 변경

- src/main/java/org/terning/terningserver/dto/auth/response/TokenGetResponseDto.java
- src/main/java/org/terning/terningserver/service/AuthServiceImpl.java
- 토큰 재발급 로직 수정
- closed #76 
- 기존 로직에서 달라진 부분은 access token 함께 반환하는 것입니다.
- dto builder에 access token 추가하여 로직을 구현하였는데 추가적으로 고려해야 하는 부분이 있다면 말씀해 주시면 좋겠습니다.
> [♻️ refactor] 토큰 재발급 로직 수정

- src/main/java/org/terning/terningserver/controller/FilterController.java
- src/main/java/org/terning/terningserver/controller/swagger/FilterSwagger.java
- src/main/resources/application-dev.yml
- src/main/resources/application.yml
- 설명
- closed #이슈번호
리뷰어들에게 하고 싶은 말
> [🔨Fix/#75]

- src/main/java/org/terning/terningserver/controller/FilterController.java
- src/main/java/org/terning/terningserver/service/FilterServiceImpl.java
- 필터링 설정 안 한 유저가 재설정시 오류나는  문제 해결
- 설명
- closed #이슈번호
리뷰어들에게 하고 싶은 말
> [🔨 fix/#82]: 필터링 재설정 로직 오류 수정

- src/main/java/org/terning/terningserver/dto/search/response/SearchResultResponseDto.java
- src/main/java/org/terning/terningserver/service/HomeServiceImpl.java
- src/main/java/org/terning/terningserver/service/SearchServiceImpl.java
- 탐색 > 검색 결과 화면 응답 데이터 변경
- closed #88 
- Swagger(200 성공)
클라에서 급하게 수정 요청을 하여 오류가 없는지 확인했고 정상적으로 출력되는 자료 첨부하였습니다!
> [🔥!hotfix/#88] 탐색 > 검색 결과 화면 응답 데이터 변경

- src/main/java/org/terning/terningserver/config/SwaggerConfig.java
- src/main/java/org/terning/terningserver/config/WebMvcConfig.java
- [✨feat] 스테이징 서버 Cors 처리 및 Swagger 설정 추가
- closed #110
> [✨feat] 스테이징 서버 Cors 처리 및 Swagger 설정 추가

- src/main/java/org/terning/terningserver/TerningserverApplication.java
- [ 🎉 deploy] 터닝 APP 릴리즈를 위한 API 최종 배포 v1.0.0 (2차 스프린트 적용사항 반영)
- closed #156
> [🎉 deploy] 터닝 APP 릴리즈를 위한 API 최종 배포 v1.0.0 (2차 스프린트 적용사항 반영)

- src/main/java/org/terning/terningserver/service/WebhookService.java
- 스테이징 환경에서는 웹훅을 비활성화하도록 코드를 수정하였습니다.
> [🔀 merge] 스테이징 환경에서는 웹훅을 비활성화하도록 코드 수정

- src/main/java/org/terning/terningserver/TerningserverApplication.java
- [🎉 deploy] 터닝 운영서버 배포 
- closed #163 
- closed #161
> [🎉 deploy] 터닝 운영서버 배포 

- src/main/java/org/terning/terningserver/service/WebhookService.java
- [🔀 merge] [2차] 스프린트 코드 리펙토링 사항을 적용합니다.
- closed #166
> [🔀 merge] [2차] 코드 리펙토링 사항 적용 (9)

- build.gradle
- src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryCustom.java
- src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java
- src/main/java/org/terning/terningserver/service/HomeServiceImpl.java
- src/test/java/org/terning/terningserver/service/legacy/HomeServicePerformanceTest.java
- 기존 `HomeService` 구현에서 발생할 수 있는 **N+1 문제**를 해결하고, 불필요한 호출을 줄여 성능을 개선하였습니다.
- 기존 코드는 각 공고별로 `scrapRepository`를 호출하여 스크랩 정보를 조회하는 방식으로, 대량 데이터 처리 시 **N+1 문제**를 유발할 가능성이 있었습니다.
- `HomeService` 클래스의 `getAnnouncements` 메서드 성능 비교 테스트 결과 정리하였습니다.
- 공고 데이터의 크기(1개, 100개, 1000개)에 따른 처리 시간과 데이터 정확성을 평가하였습니다.
```java
List<HomeResponseDto> responseDtos = announcements.stream()
.map(announcement -> {
boolean isScrapped = scrapRepository.existsByInternshipAnnouncementIdAndUserId(announcement.getId(), userId);
String color = scrapRepository.findColorByInternshipAnnouncementIdAndUserId(announcement.getId(), userId);
return HomeResponseDto.of(announcement, isScrapped, color);
})
.toList();
```
- 문제점:
- 각 공고마다 별도의 쿼리가 실행되어, 공고 데이터가 많아질수록 DB 호출 횟수가 기하급수적으로 증가.
- 이는 대규모 데이터(예: 1000개 공고) 처리 시 성능 저하를 초래. …
> [♻️ refactor/#175]: 공고 데이터 조회 성능 최적화 및 N+1 문제 해결

- src/main/java/org/terning/terningserver/service/FilterServiceImpl.java
- 온보딩 건너뛰기 시, 클라에서 null값을 받아올 수 있도록 API를 수정했습니다
> [🔥 !hotfix] 직무필터링, 사용자 필터링 정보, 필터링 재설정(직무, 계획) API 수정

- .github/workflows/DOCKER-CD-STAGING.yml
- .github/workflows/DOCKER-CD.yml
- src/main/java/org/terning/terningserver/config/SwaggerConfig.java
- src/main/java/org/terning/terningserver/config/WebMvcConfig.java
- [🔥 !hotfix] [3차] 스테이징 서버 마이그레이션 진행
> [🔥 !hotfix] [3차] 스테이징 서버 마이그레이션 진행

- README.md
- src/main/java/org/terning/terningserver/auth/application/signup/AuthSignUpServiceImpl.java
- [🔀 merge] [4차] 코드 리펙토링 사항 적용 (4)
> [🔀 merge] [4차] 코드 리펙토링 사항 적용 (4)

- README.md
- src/main/java/org/terning/terningserver/auth/application/signup/AuthSignUpServiceImpl.java
-  HTTP 요청/응답 수정사항 로깅 스테이징 서버 반영합니다.
- closed #227
> [🔀 merge] HTTP 요청/응답 수정사항 로깅 스테이징 서버 반영

- src/main/java/org/terning/terningserver/user/dto/response/ProfileResponseDto.java
- [🔀 merge] [4차] 코드 리펙토링 사항 메인 서버에 적용
> [🔀 merge] [4차] 코드 리펙토링 사항 메인 서버에 적용

- .github/workflows/DOCKER-CD-STAGING.yml
- src/main/resources/application.yml
- 무중단 배포 스크립트 안정성 강화 및 오류 처리 개선
> [Merge] : 무중단 배포 스크립트 안정성 강화 및 오류 처리 개선

- .github/workflows/DOCKER-CD-STAGING.yml
- src/main/resources/application.yml
-  배포 스크립트 내 JSON 환경변수 파싱 오류 수정
> [Merge] 배포 스크립트 내 JSON 환경변수 파싱 오류 수정

- .github/workflows/DOCKER-CD-STAGING.yml
- JAVA_OPTS 누락으로 인한 컨테이너 실행 실패 및 헬스 체크 오류 해결
> [Merge] :  JAVA_OPTS 누락으로 인한 컨테이너 실행 실패 및 헬스 체크 오류 해결

- src/main/java/org/terning/terningserver/auth/application/AuthService.java
- src/main/java/org/terning/terningserver/auth/dto/response/SignInResponse.java
- 회원가입 시 authId의 Bearer 접두사 처리
> merge : 회원가입 시 authId의 Bearer 접두사 처리
